apiVersion: v1
data:
  wg0.conf: |
    [Interface]
    Address = 10.200.20.10
    PrivateKey = EFP0e7ygpNdGMfOuhnm2lLIsRH2oBL7yPuEieoQwqHo=
    ListenPort = 51820

    [Peer]
    PublicKey = hZ5ezbcz6mffgMATuuMRIbTt/kF68rtgp19r1NXzIk4=
    Endpoint = 10.0.0.224:31821
    AllowedIPs = 10.245.0.0/16

kind: ConfigMap
metadata:
  name: anchor3-upf-vpn
