apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-smf-02-configmap
data:
  smfcfg.yaml: |
    info:
      version: 1.0.2
      description: SMF initial local configuration

    configuration:
      smfName: SMF
      sbi:
        scheme: http
        registerIPv4: free5gc-smf-02-svc # IP used to register to NRF
        bindingIPv4: free5gc-smf-02-svc  # IP used to bind the service
        port: 8000
        tls:
          key: free5gc/support/TLS/smf.key
          pem: free5gc/support/TLS/smf.pem
      serviceNameList:
        - nsmf-pdusession
        - nsmf-event-exposure
        - nsmf-oam
      snssaiInfos:
        - sNssai:
            sst: 1
            sd: 112233
          dnnInfos:
            - dnn: internet
              dns: 
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860::8888
      pfcp:
        addr: free5gc-smf-02-svc
      userplane_information:
        up_nodes:
          gNB1:
            type: AN
          BranchingUPF:
            type: UPF
            node_id: 10.200.10.6
            sNssaiUpfInfos:
              - sNssai:
                  sst: 1
                  sd: 112233
                dnnUpfInfoList:
                  - dnn: internet
            interfaces:
              - interfaceType: N3
                endpoints:
                  - 10.245.1.11
                networkInstance: internet
              - interfaceType: N9
                endpoints:
                  - 10.245.1.11
                networkInstance: internet
          AnchorUPF1:
            type: UPF
            node_id: free5gc-upf-a3-svc
            sNssaiUpfInfos:
              - sNssai:
                  sst: 1
                  sd: 112233
                dnnUpfInfoList:
                  - dnn: internet
                    pools:
                      - cidr: 60.61.0.0/16
            interfaces:
              - interfaceType: N9
                endpoints:
                  - 10.200.20.10
                networkInstance: internet
          AnchorUPF2:
            type: UPF
            node_id: 10.200.10.7
            interfaces:
              - interfaceType: N9
                endpoints:
                  - 10.245.1.14
                networkInstance: internet
        links:
          - A: gNB1
            B: BranchingUPF
          - A: BranchingUPF
            B: AnchorUPF1
          - A: BranchingUPF
            B: AnchorUPF2
      nrfUri: http://free5gc-nrf-svc:8000
      locality: area1
      ulcl: true

    logger:
      SMF:
        debugLevel: info
        ReportCaller: false
      NAS:
        debugLevel: info
        ReportCaller: false
      NGAP:
        debugLevel: info
        ReportCaller: false
      Aper:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false
      PFCP:
        debugLevel: info
        ReportCaller: false

  uerouting.yaml: |
    info:
      version: 1.0.1
      description: Routing information for UE

    ueRoutingInfo: # the list of UE routing information
      UE1: # Group Name
        members:
        - imsi-208930000000004 # Subscription Permanent Identifier of the UE
        topology: # Network topology for this group (Uplink: A->B, Downlink: B->A)
        # default path derived from this topology
        # node name should be consistent with smfcfg.yaml
          - A: gNB1
            B: BranchingUPF
          - A: BranchingUPF
            B: AnchorUPF1
          - A: BranchingUPF
            B: AnchorUPF2
        specificPath:
          - dest: 10.20.1.0/24 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            path: [BranchingUPF, AnchorUPF2]
          - dest: 10.0.0.0/24 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            path: [BranchingUPF, AnchorUPF1]
      UE2: # Group Name
        members:
        - imsi-208930000000006 # Subscription Permanent Identifier of the UE
        topology: # Network topology for this group (Uplink: A->B, Downlink: B->A)
        # default path derived from this topology
        # node name should be consistent with smfcfg.yaml
          - A: gNB1
            B: BranchingUPF
          - A: BranchingUPF
            B: AnchorUPF1
          - A: BranchingUPF
            B: AnchorUPF2
        specificPath:
          - dest: 10.20.1.0/24 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            path: [BranchingUPF, AnchorUPF2]
          - dest: 10.0.0.0/24 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            path: [BranchingUPF, AnchorUPF1]
---
apiVersion: v1
kind: Service
metadata:
  name: free5gc-smf-02-svc
spec:
  selector:
    app: free5gc-smf-02
  clusterIP: None # 10.96.100.3
  ports:
    - name: sbi
      protocol: TCP
      port: 29502
    - name: pfcp
      protocol: UDP
      port: 8805
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-smf-02-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-smf-02
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-smf-02
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/free5gc-control-plane:stage3.0.6-amd64
        command: ["/bin/sh"]
        args: ["-c", "sleep 5s && ./bin/smf -smfcfg ./config/smfcfg.yaml -uerouting ./config/uerouting.yaml"]
        env:
        - name: GIN_MODE
          value: debug # debug | release
        volumeMounts:
        - name: smfcfg
          mountPath: free5gc/config/smfcfg.yaml
          subPath: smfcfg.yaml
        - name: uerouting
          mountPath: free5gc/config/uerouting.yaml
          subPath: uerouting.yaml
      volumes:
      - name: smfcfg
        configMap:
          name: free5gc-smf-02-configmap
          items: 
          - key: smfcfg.yaml
            path: smfcfg.yaml
      - name: uerouting
        configMap:
          name: free5gc-smf-02-configmap
          items: 
          - key: uerouting.yaml
            path: uerouting.yaml
      

