apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-gnb-deployment
  labels:
    app: ueransim-gnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ueransim-gnb
  template:
    metadata:
      labels:
        app: ueransim-gnb
    spec:
      containers:
      - name: ueransim-gnb
        imagePullPolicy: IfNotPresent
        image: free5gmano/ueransim:v3.1.4
        securityContext:
          privileged: true
        command: ["/bin/bash", "-c"]
        args: ["./build/nr-gnb -c ./config/free5gc-gnb.yaml"]
        volumeMounts:
        - name: gnb-conf
          mountPath: /UERANSIM/config/free5gc-gnb.yaml
          subPath: free5gc-gnb.yaml
      initContainers:
        - name: wireguard-client
          image: newnoobtank/wg-vpn
          command: [ "/bin/bash", "-c", "wg-quick up wg0" ]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
          volumeMounts:
            - name: wg-client-config
              mountPath: /etc/wireguard/
            - name: host-volumes
              mountPath: /lib/modules
      volumes:
      - name: host-volumes
        hostPath:
          path: /lib/modules
          type: Directory
      - name: wg-client-config
        configMap:
          name: ran-upf-vpn
          items:
          - key: wg0.conf
            path: wg0.conf
      - name: gnb-conf
        configMap:
          name: ueransim-configmap
          items:
          - key: free5gc-gnb.yaml
            path: free5gc-gnb.yaml
